name: absensi_app
description: Aplikasi Absensi Digital dengan Face Recognition & RFID
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1

  # Database & Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  sqflite: ^2.3.0

  #gps
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0

  # Camera & Image
  camera: ^0.10.5+9
  image_picker: ^1.0.5
  image: ^4.1.7

  # Face Recognition
  google_mlkit_face_detection: ^0.11.0

  #fingerprint
  local_auth: ^2.1.7

  # Backend
  http: ^1.2.2
  web_socket_channel: ^2.4.0

  # Utilities
  audioplayers: ^5.2.1
  connectivity_plus: ^5.0.2
  intl: ^0.18.0
  supabase: ^2.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/models/
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon/logo.png"
